// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package neferclientmocks

import (
	"github.com/bnema/neferclient"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockHandler
func (_mock *MockHandler) Error(err error) {
	_mock.Called(err)
	return
}

// MockHandler_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockHandler_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - err error
func (_e *MockHandler_Expecter) Error(err any) *MockHandler_Error_Call {
	return &MockHandler_Error_Call{Call: _e.mock.On("Error", err)}
}

func (_c *MockHandler_Error_Call) Run(run func(err error)) *MockHandler_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_Error_Call) Return() *MockHandler_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_Error_Call) RunAndReturn(run func(err error)) *MockHandler_Error_Call {
	_c.Run(run)
	return _c
}

// FDReady provides a mock function for the type MockHandler
func (_mock *MockHandler) FDReady(id uint64) {
	_mock.Called(id)
	return
}

// MockHandler_FDReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FDReady'
type MockHandler_FDReady_Call struct {
	*mock.Call
}

// FDReady is a helper method to define mock.On call
//   - id uint64
func (_e *MockHandler_Expecter) FDReady(id any) *MockHandler_FDReady_Call {
	return &MockHandler_FDReady_Call{Call: _e.mock.On("FDReady", id)}
}

func (_c *MockHandler_FDReady_Call) Run(run func(id uint64)) *MockHandler_FDReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_FDReady_Call) Return() *MockHandler_FDReady_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_FDReady_Call) RunAndReturn(run func(id uint64)) *MockHandler_FDReady_Call {
	_c.Run(run)
	return _c
}

// OutputAdded provides a mock function for the type MockHandler
func (_mock *MockHandler) OutputAdded(out *neferclient.Output) {
	_mock.Called(out)
	return
}

// MockHandler_OutputAdded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutputAdded'
type MockHandler_OutputAdded_Call struct {
	*mock.Call
}

// OutputAdded is a helper method to define mock.On call
//   - out *neferclient.Output
func (_e *MockHandler_Expecter) OutputAdded(out any) *MockHandler_OutputAdded_Call {
	return &MockHandler_OutputAdded_Call{Call: _e.mock.On("OutputAdded", out)}
}

func (_c *MockHandler_OutputAdded_Call) Run(run func(out *neferclient.Output)) *MockHandler_OutputAdded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *neferclient.Output
		if args[0] != nil {
			arg0 = args[0].(*neferclient.Output)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_OutputAdded_Call) Return() *MockHandler_OutputAdded_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_OutputAdded_Call) RunAndReturn(run func(out *neferclient.Output)) *MockHandler_OutputAdded_Call {
	_c.Run(run)
	return _c
}

// OutputRemoved provides a mock function for the type MockHandler
func (_mock *MockHandler) OutputRemoved(global uint32) {
	_mock.Called(global)
	return
}

// MockHandler_OutputRemoved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OutputRemoved'
type MockHandler_OutputRemoved_Call struct {
	*mock.Call
}

// OutputRemoved is a helper method to define mock.On call
//   - global uint32
func (_e *MockHandler_Expecter) OutputRemoved(global any) *MockHandler_OutputRemoved_Call {
	return &MockHandler_OutputRemoved_Call{Call: _e.mock.On("OutputRemoved", global)}
}

func (_c *MockHandler_OutputRemoved_Call) Run(run func(global uint32)) *MockHandler_OutputRemoved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint32
		if args[0] != nil {
			arg0 = args[0].(uint32)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_OutputRemoved_Call) Return() *MockHandler_OutputRemoved_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_OutputRemoved_Call) RunAndReturn(run func(global uint32)) *MockHandler_OutputRemoved_Call {
	_c.Run(run)
	return _c
}
